# Generated by Django 3.1 on 2020-08-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloudname', models.CharField(max_length=200)),
                ('data', models.CharField(max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
